name: Flask CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/deployment.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
          pip install -r tests/requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
      - name: Run tests
        run: pytest tests/

  build-and-push:
    needs: test
    env:
      REGISTRY: ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}


      - name: Extract metadata
        id: meta
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/flask-app:${{ env.IMAGE_TAG }} .
          docker push ghcr.io/${{ github.actor }}/flask-app:${{ env.IMAGE_TAG }}

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|ghcr.io/your-username/flask-app:.*|ghcr.io/${{ github.actor }}/flask-app:${{ env.IMAGE_TAG }}|" k8s/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push
